data:
  train_path: "data/raw/train.csv"
  test_path: "data/raw/test.csv"
  validation_split_date: "2025-06-13"
  processed_dir: "data/processed/"
  features_dir: "data/features/"

features:
  use_basic: true
  use_behavioral: true
  use_temporal: true
  use_research: true
  correlation_threshold: 0.05
  max_features: 30
  remove_correlated_threshold: 0.85

models:
  ensemble_weights:
    lightgbm: 0.4
    xgboost: 0.3
    catboost: 0.2
    random_forest: 0.1
  
  lightgbm:
    objective: "regression"
    metric: "rmse"
    num_leaves: 63
    learning_rate: 0.05
    feature_fraction: 0.8
    bagging_fraction: 0.8
    bagging_freq: 5
    min_data_in_leaf: 50
    reg_alpha: 1.0
    reg_lambda: 1.0
    random_state: 42
    n_estimators: 500
    
  xgboost:
    objective: "reg:squarederror"
    learning_rate: 0.05
    max_depth: 8
    min_child_weight: 3
    subsample: 0.8
    colsample_bytree: 0.8
    reg_alpha: 0.1
    reg_lambda: 0.1
    random_state: 42
    n_estimators: 500
    
  catboost:
    objective: "RMSE"
    learning_rate: 0.05
    depth: 8
    l2_leaf_reg: 3
    random_seed: 42
    iterations: 500
    verbose: false
    
  random_forest:
    n_estimators: 300
    max_depth: 12
    min_samples_split: 15
    min_samples_leaf: 8
    max_features: "sqrt"
    random_state: 42

evaluation:
  cv_folds: 5
  temporal_validation: true
  test_size: 0.2
  metrics: ["mse", "rmse", "mae", "r2"]
  
logging:
  level: "INFO"
  format: "%(asctime)s - %(name)s - %(levelname)s - %(message)s"