data:
  train_path: "data/raw/train.csv"
  test_path: "data/raw/test.csv"
  validation_split_date: "2025-06-13"
  
features:
  use_basic: true
  use_behavioral: true
  use_temporal: true
  use_research: true
  correlation_threshold: 0.05
  
models:
  random_forest:
    n_estimators: 300
    max_depth: 12
    min_samples_split: 15
    min_samples_leaf: 8
    random_state: 42
  
evaluation:
  cv_folds: 5
  metrics: ["mse", "rmse", "mae"]